version: "3.9"

services:
  database:
    build:
      context: .
      dockerfile: PostgresDockerfile
    image: my-custom-postgres
    container_name: my-postgres-container
    ports:
      - "3306:3306"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  app:
    container_name: demo
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: ProductServiceDockerfile
    ports:
      - "8085:8085"
    depends_on:
      - database
      - rabbitmq-container
    volumes:
      - ./:/app/app
    links:
      - database
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

networks:
  app-network:
    external:
      name: app-network
    driver: bridge

volumes:
  postgres-data:

